### ISSUE TITLE
💄 navbar 작아졌을 경우 스크롤 표시

### ISSUE THREAD

**Issue by jis-kim** [innovationacademy-kr/our42vent#109]
## 내용
- 현재 화면이 작아지면 navbar의 카테고리가 잘려서 나옵니다.
- 스크롤 표시로 사용자에게 스크롤이 가능하다는 것을 보여주는 것이 좋을 것 같습니다!
## 스크린샷
<img width="626" alt="Screen Shot 2022-01-26 at 6 35 41 PM" src="https://user-images.githubusercontent.com/71019735/151138787-f1bc838c-5f2a-412a-a8a9-a22255e923eb.png">

**Comment by yongjulejule** [comment]
고맙읍니다
