### ISSUE TITLE
✨클라이언트 사이드 axios 에러 핸들링

### ISSUE THREAD

**Issue by yongjulejule** [innovationacademy-kr/our42vent#110]
## 내용
axios 에러시 상황에 맞게 리다이렉션이나 모달 창 띄우기

발견 사례들은 코멘트로 남기고 커밋할때 이슈 태그 해주세요~~

**Comment by yongjulejule** [comment]
https://github.com/innovationacademy-kr/our42vent/blob/da2a43caeee06fba40f2785e5bdaf4c3eddc9f9e/public/javascripts/eventList/addClickListenerForEdit.js#L47
모달 창 이후 than 을 이용하여 리다이렉션 해주기

**Comment by jis-kim** [comment]
#164 으로 처리되어 close 하였습니다.
