### ISSUE TITLE
:bug: 인트라 이벤트 업데이트 실패

### ISSUE THREAD

**Issue by 42ghan** [innovationacademy-kr/our42vent#113]
## 발생 일시
20220127 13:30
## 발생 위치
- 서버 `/db/getIntraEvents/getUpdatedEvents.js`
## 증상
- 제가 13:30 쯤 `develop` merge 했습니다.
- 아래 스크린샷 (`~/log/our42vent/updateEvents.log`)과 같이 현재 `develop` merge 된 시점부터 cron 으로 돌고있는 `getUpdatedEvents.js` mysql connection 실패하고 있습니다.
- 직접 node 로 script 돌리면 문제 없이 돌아가고 `.env` 변수들도 이상없이 들어가는 것 확인했습니다. cron 으로 돌아가는게 뭔가 오류가 있는 것 같아요.
- @jis-kim 아마 여기서 path 넣었던게 pull 받으면서 사라져서 그런 것 같습니다. 제가 이 부분 공휴일 caching 하면서 처리했으니까 제 PR 머지 된후에도 안 고쳐지면 고민해보죠. cron job 은 주석 처리해두겠습니다.
https://github.com/innovationacademy-kr/our42vent/blob/7fd4a8f72c42bdeae574aadb7e406c18bc21c9c1/config/createRedisClient.js#L5
## 스크린샷
![Screen Shot 2022-01-27 at 4 10 51 PM](https://user-images.githubusercontent.com/83805691/151310108-0a434ba2-d60c-4cef-b37b-60d846256684.png)

**Comment by 42ghan** [comment]
cron job 주석은 다시 풀어뒀습니다.

**Comment by jis-kim** [comment]
직접 script 돌리신 위치가 어디신지 말해주실 수 있나요? 서버에서 `dotenv.config()` 직접 수정해주지 않으면 cron으로는 당연히 안됩니다..!

**Comment by 42ghan** [comment]
`/db/getIntraEvents/getUpdatedEvents.js` 여기에서 돌렸었어요.

**Comment by 42ghan** [comment]
제 PR 에서 `.env` 위치 잡아주니까 merge 되면 고쳐질 것 같네요... 굳이 지금 더 테스트 할 필요는 없을 것 같습니다.

**Comment by jis-kim** [comment]
서버 정상 실행 확인했습니다!
