### ISSUE TITLE
🐛  내가 만든 이벤트가 없을 때 홈으로 리다이렉션 됨

### ISSUE THREAD

**Issue by jis-kim** [innovationacademy-kr/our42vent#116]
## 발생 일시
2022.01.27
## 발생 위치
내가 만든 이벤트 버튼
## 증상
내가 만든 이벤트 페이지가 아니라 홈으로 리다이렉션
## 재현 방법
이벤트를 생성하지 않고 내가 만든 이벤트 버튼 누르기

**Comment by jis-kim** [comment]
내가 만든 이벤트가 있을 때도 페이지 들렀다가 바로 리다이렉션 됩니다... 😕

**Comment by yongjulejule** [comment]
에러핸들링을 적절하게 하지 않아서 생기는 문제였습니다. 고쳐 놓았으니 가능한 빨리 반영하겠습니다.
