### ISSUE TITLE
:bug: 이벤트 상세정보 팝업 장소 vw 1080p 이상일 때 align 어긋나는 현상

### ISSUE THREAD

**Issue by 42ghan** [innovationacademy-kr/our42vent#124]
## 발생 일시
20220129
## 발생 위치
- `/public/stylesheets/components/popups/event_details.css`
## 증상
- 아래 영상과 같이 이벤트 상세정보 팝업 장소 vw 1080p 이상일 때 align 어긋납니다.
- 그리고 시간 & 장소 위아래 간격 조금씩 줄여주면 좋을 것 같습니다. (모바일 & 데스크탑 둘 다)
## 스크린샷
https://user-images.githubusercontent.com/83805691/151575710-dfbcc8e2-19aa-4d3b-91e9-53e1542beb1d.mov

**Comment by 42ghan** [comment]
제가 지금 이벤트 상세정보 팝업에서 등록 취소 기능 만들어 놨는데, 내일 고쳐주시고 제 pr 에 반영하거나 어디가 문제인지 알려주시면 제가 고치겠습니다.

**Comment by 42ghan** [comment]
limit 에 가까운 양의 텍스트 넣었을 때 버튼 짤립니다.
<img width="1792" alt="Screen Shot 2022-01-29 at 1 05 02 AM" src="https://user-images.githubusercontent.com/83805691/151580774-0b80bc7d-434e-45bb-ab7f-0ea7c4257713.png">

**Comment by yongjulejule** [comment]
🤯🤯🤯
