### ISSUE TITLE
:bug: /:param 자리에 다른 타입을 넣으면 서버가 터짐

### ISSUE THREAD

**Issue by jis-kim** [innovationacademy-kr/our42vent#128]
## 발생 일시
2022.01.29
## 발생 위치
/event/:id 등 많은 URI들
## 증상
get요청을 형식에 맞지않게 보내면 그대로 서버가 다운됩니다.
## 재현 방법
/event/[string 타입] 넣어주기..
## 스크린샷
<img width="387" alt="Screen Shot 2022-01-29 at 8 50 22 PM" src="https://user-images.githubusercontent.com/71019735/151660268-8d28ee78-7c17-48a8-a15f-b185e70bb140.png">

- Number로 convert하신 후 NaN 체크하시면 될 것 같습니다.

**Comment by kenu** [comment]
제가 써본 적은 없지만, 참고해 보세요.
To have more control over the exact string that can be matched by a route parameter, you can append a regular expression in parentheses (()):

Route path: /user/:userId(\d+)
Request URL: http://localhost:3000/user/42
req.params: {"userId": "42"}
from: https://expressjs.com/en/guide/routing.html
