### ISSUE TITLE
:bug: firefox 에서 각기 다른 more 버튼 순차적으로 누르면 창이 안 사라지는 현상

### ISSUE THREAD

**Issue by 42ghan** [innovationacademy-kr/our42vent#130]
## 발생 일시
20220130
## 발생 위치
- 캘린더 뷰
- `loadMore()` 함수 (/public/javascripts/calendar/month/addListenersAfterRender.js)
## 증상
- firefox 에서 각기 다른 날짜의 more 버튼 순차적으로 누르면 창이 안 사라진다.
- 버튼이 아닌 곳 누르면 사라진다.
- chrome 은 괜찮고 firefox 는 버그, 다른 브라우저들도 테스트 필요
## 스크린샷
<img width="1792" alt="Screen Shot 2022-01-30 at 2 28 57 AM" src="https://user-images.githubusercontent.com/83805691/151671293-0de46c30-46f4-4015-b8d8-87644dd07290.png">

**Comment by jis-kim** [comment]
whale은 해당 현상 나타나지 않습니다. safari는 more버튼이 작동을 안하네요....
