### ISSUE TITLE
🐛  login 페이지에서 페이지 렌더링 오류

### ISSUE THREAD

**Issue by yongjulejule** [innovationacademy-kr/our42vent#24]
## 발생 일시
210105 23:10
## 발생 위치
login.js & login.ejs
## 증상
layout: false로 login.ejs에 보내는데,  title이 정해지지 않은 채 <%- title %>를 호출하여 에러가 남
## 재현 방법
로그인 즉시 터짐!
## 해결 방법
login에서만 쓰는 페이지이니, title을 ejs로 주지 말고 그냥 텍스트를 넣거나,  {title: 'login'}같은 방식으로 login.js에 추가해주면 됨

**Comment by yongjulejule** [comment]
혹시 테스트 하고 싶으신데, 버그떠서 킹받으실까봐 남겨둡니다

**Comment by 42ghan** [comment]
어 저거 제가 저렇게 푸쉬했군요... 맨... login.ejs 에 <title>을 굳이 render 할때 받을 필요가 없을 것 같아서 뺐는데 끝까지 수정을 안 했군요..하하 수정하고 푸쉬하겠습니다.

**Comment by yongjulejule** [comment]
레이아웃 false를 주고 login에서 login.ejs로 렌더 하는데 여기서도 title을 씁니다...  근데 title을 안넘겨 줬더라군요! 지한이 리펙토링하다 실수한듯
