### ISSUE TITLE
🐛 mysql2 사용시 pool 동기화 문제

### ISSUE THREAD

**Issue by yongjulejule** [innovationacademy-kr/our42vent#35]
## 발생 일시
20220107 14:30~16:30
## 발생 위치
app.js
initConnections.js
insertNewUser.js
## 증상
app.js에서 pool을 연결해서 들고 오려고 했습니다. 이때 createPool은 비동기로 작동하여 pool이 업데이트가 되지 않습니다.

이 pool을 갖고 insertNewUser에 가서 pool.query를 호출합니다. 당연히 pool에는 query란 메소드가 없겠죠? ㅎㅎ 
바로 pool이 pool이 아니기 때문입니다 짜잔!

## 재현 방법
로그인 버튼을 누르십시오!
## 스크린샷
<img width="736" alt="Screen Shot 2022-01-07 at 4 41 26 PM" src="https://user-images.githubusercontent.com/79127797/148509334-010da6af-a3bb-4c0b-88e1-e1a0c76c61f8.png">

+)

<img width="645" alt="Screen Shot 2022-01-07 at 4 57 42 PM" src="https://user-images.githubusercontent.com/79127797/148511229-f438f568-3868-4195-ae08-2a20ac751b84.png">
mysql2 npm 문서를 보면 (err, rows, fields) 순서로 인자가 들어가는데, 첫번째 인자에 query 결과 값이 나옴.... err 가 결과임.... 이게뭐람....

**Comment by jis-kim** [comment]
`app.js`에서 `const pool = initConnection()`으로 받아온 pool이 `insertNewUser`로 먼저 넘어가버려서 작동이 안되는 문제입니다. mysql2를 쓰지 않고 mysql을 쓰면 바로 해결될 문제지만 혹시 동기적으로 처리가 가능한 방법을 아시는 분이 있으시다면 제발 해결을 해주세요. 감사합니다. 줄레 : 제발요

**Comment by yongjulejule** [comment]
로컬환경을 활용하여 해결~!~~!!
다른 방법은 [여기](https://github.com/innovationacademy-kr/our42vent/commit/704ca3a2f83b949a1b1400fcff896767f1a7597b)
