### ISSUE TITLE
📝 CONTRIBUTION.md 에 로그 포맷, 파일명, import 순서 convention 추가

### ISSUE THREAD

**Issue by 42ghan** [innovationacademy-kr/our42vent#58]
## 내용
- CONTRIBUTION.md 에 로그 포맷, 파일명, import 순서 convention 추가

**Comment by yongjulejule** [comment]
@jis-kim @sehhong3317 @42ghan  헉 저희 오늘 이거 했어야 했는데 까먹었네요... 내일 회의때 합시다~~
