### ISSUE TITLE
🐛  브라우저 환경마다 쿠키 설정이 달라짐

### ISSUE THREAD

**Issue by yongjulejule** [innovationacademy-kr/our42vent#75]
## 발생 일시
2021 01 17 13:25분경

## 발생 위치
safari 브라우저 및 firefox 브라우저로 접속시

## 증상
safari 브라우저로 접속하면 로그인 후 로그인 화면으로 리다이렉트됨.
cookie 속성에 secure: true를 해제하면 정상적으로 로그인 가능.
safari 는 서버에 올리고 https로 테스트 하는걸로...

firefox 브라우저는 refreshToken, accessToken의 쿠키 expire 시간이 Session으로 설정됨.

## 재현 방법
사파리 및 파이어폭스로 로그인하면 됩니다,,,

**Comment by jis-kim** [comment]
safari 서버에서는 로그인이 잘 됩니다 : ] http를 거르네요!

**Comment by yongjulejule** [comment]
파이어폭스는 브라우저 설정에서 따로 설정해 주지 않으면 쿠키 만료 시간을 줄 수 없고 session으로 고정되는게 기본값이네요,,,
